
version: '3'
services:
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    ports:
      - 5601:5601
    environment:
      - "OPENSEARCH_HOSTS=https://opensearch-node1:9200"
  
  opensearch-node1:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    depends_on:
      - opensearch-dashboards
  
volumes:
  opensearch-data1:
    driver: local